linters:
  enable:
    - cyclop
    - bodyclose
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gomnd
    - gosec
    - interfacer
    - maligned
    - misspell
    - nakedret
    - nestif
    - prealloc
    - unconvert
    - unparam
    - wsl
