linters:
  enable:
    - cyclop
    - bodyclose
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gomnd
    - gosec
    - interfacer
    - maligned
    - misspell
    - nakedret
    - nestif
    - prealloc
    - unconvert
    - unparam
    - wsl
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - style
    - test
    - unused
  disable:
    - testpackage
    - varnamelen
issues:
  exclude-rules:
    # False positive: https://github.com/kunwardeep/paralleltest/issues/8.
    - linters:
        - paralleltest
      text: "does not use range value in test Run"
